import { Question } from './types';

export const QUIZ_QUESTIONS: Question[] = [
  {
    id: '1',
    type: 'conjugaison',
    verb: 'être',
    category: 'être',
    pronoun: 'Je',
    tense: 'présent',
    sentence: 'Je ___ à l\'école.',
    correctAnswer: 'suis',
    options: ['suis', 'es', 'est', 'sommes'],
  },
  {
    id: '2',
    type: 'conjugaison',
    verb: 'avoir',
    category: 'avoir',
    pronoun: 'Tu',
    tense: 'présent',
    sentence: 'Tu ___ un beau vélo.',
    correctAnswer: 'as',
    options: ['ai', 'as', 'a', 'avez'],
  },
  {
    id: '3',
    type: 'conjugaison',
    verb: 'chanter',
    category: '1er groupe',
    pronoun: 'Elle',
    tense: 'présent',
    sentence: 'Elle ___ une chanson.',
    correctAnswer: 'chante',
    options: ['chante', 'chantes', 'chantent', 'chantons'],
  },
  {
    id: '4',
    type: 'conjugaison',
    verb: 'aller',
    category: 'aller',
    pronoun: 'Nous',
    tense: 'présent',
    sentence: 'Nous ___ au parc.',
    correctAnswer: 'allons',
    options: ['allons', 'allez', 'vont', 'vais'],
  },
  {
    id: '5',
    type: 'conjugaison',
    verb: 'manger',
    category: '1er groupe',
    pronoun: 'Vous',
    tense: 'présent',
    sentence: 'Vous ___ des cerises.',
    correctAnswer: 'mangez',
    options: ['mange', 'manges', 'mangez', 'mangent'],
  },
  {
    id: '6',
    type: 'conjugaison',
    verb: 'être',
    category: 'être',
    pronoun: 'Ils',
    tense: 'présent',
    sentence: 'Ils ___ très gentils.',
    correctAnswer: 'sont',
    options: ['sont', 'sommes', 'êtes', 'est'],
  },
  {
    id: '7',
    type: 'conjugaison',
    verb: 'avoir',
    category: 'avoir',
    pronoun: 'Nous',
    tense: 'présent',
    sentence: 'Nous ___ faim.',
    correctAnswer: 'avons',
    options: ['avons', 'avez', 'ont', 'ai'],
  },
  {
    id: '8',
    type: 'conjugaison',
    verb: 'jouer',
    category: '1er groupe',
    pronoun: 'Tu',
    tense: 'présent',
    sentence: 'Tu ___ au ballon.',
    correctAnswer: 'joues',
    options: ['joue', 'joues', 'jouen', 'jouons'],
  },
  {
    id: '9',
    type: 'conjugaison',
    verb: 'aller',
    category: 'aller',
    pronoun: 'Je',
    tense: 'présent',
    sentence: 'Je ___ chez le dentiste.',
    correctAnswer: 'vais',
    options: ['vais', 'vas', 'va', 'vont'],
  },
  {
    id: '10',
    type: 'conjugaison',
    verb: 'aimer',
    category: '1er groupe',
    pronoun: 'On',
    tense: 'présent',
    sentence: 'On ___ le chocolat.',
    correctAnswer: 'aime',
    options: ['aime', 'aimes', 'aimons', 'aimez'],
  },
  {
    id: '11',
    type: 'conjugaison',
    verb: 'faire',
    category: 'faire',
    pronoun: 'Je',
    tense: 'présent',
    sentence: 'Je ___ mes devoirs.',
    correctAnswer: 'fais',
    options: ['fais', 'fait', 'faisons', 'font'],
  },
  {
    id: '12',
    type: 'conjugaison',
    verb: 'faire',
    category: 'faire',
    pronoun: 'Vous',
    tense: 'présent',
    sentence: 'Vous ___ du sport.',
    correctAnswer: 'faites',
    options: ['faites', 'faisons', 'font', 'fait'],
  },
  {
    id: '13',
    type: 'conjugaison',
    verb: 'dire',
    category: 'dire',
    pronoun: 'Tu',
    tense: 'présent',
    sentence: 'Tu ___ la vérité.',
    correctAnswer: 'dis',
    options: ['dis', 'dit', 'disons', 'dites'],
  },
  {
    id: '14',
    type: 'conjugaison',
    verb: 'dire',
    category: 'dire',
    pronoun: 'Ils',
    tense: 'présent',
    sentence: 'Ils ___ bonjour.',
    correctAnswer: 'disent',
    options: ['disent', 'dit', 'disons', 'dis'],
  },
  {
    id: '15',
    type: 'conjugaison',
    verb: 'venir',
    category: 'venir',
    pronoun: 'Elle',
    tense: 'présent',
    sentence: 'Elle ___ de Paris.',
    correctAnswer: 'vient',
    options: ['viens', 'vient', 'venons', 'viennent'],
  },
  {
    id: '16',
    type: 'conjugaison',
    verb: 'venir',
    category: 'venir',
    pronoun: 'Nous',
    tense: 'présent',
    sentence: 'Nous ___ te voir.',
    correctAnswer: 'venons',
    options: ['venons', 'venez', 'viennent', 'viens'],
  },
  {
    id: '17',
    type: 'conjugaison',
    verb: 'manger',
    category: '1er groupe',
    pronoun: 'J\'',
    tense: 'passé composé',
    sentence: 'J\'ai ___ une pomme.',
    correctAnswer: 'mangé',
    options: ['mangé', 'manger', 'mangez', 'manges'],
  },
  {
    id: '18',
    type: 'conjugaison',
    verb: 'finir',
    category: '1er groupe',
    pronoun: 'Tu',
    tense: 'passé composé',
    sentence: 'Tu as ___ tes devoirs.',
    correctAnswer: 'fini',
    options: ['fini', 'finis', 'finir', 'finie'],
  },
  {
    id: '19',
    type: 'conjugaison',
    verb: 'être',
    category: 'être',
    pronoun: 'Il',
    tense: 'passé composé',
    sentence: 'Il a ___ sage.',
    correctAnswer: 'été',
    options: ['été', 'êtes', 'était', 'est'],
  },
  {
    id: '20',
    type: 'conjugaison',
    verb: 'avoir',
    category: 'avoir',
    pronoun: 'Nous',
    tense: 'passé composé',
    sentence: 'Nous avons ___ de la chance.',
    correctAnswer: 'eu',
    options: ['eu', 'eus', 'eut', 'avez'],
  },
  {
    id: '21',
    type: 'conjugaison',
    verb: 'faire',
    category: 'faire',
    pronoun: 'Vous',
    tense: 'passé composé',
    sentence: 'Vous avez ___ un gâteau.',
    correctAnswer: 'fait',
    options: ['fait', 'fais', 'faites', 'faire'],
  },
  {
    id: '22',
    type: 'conjugaison',
    verb: 'manger',
    category: '1er groupe',
    pronoun: 'Je',
    tense: 'futur proche',
    sentence: 'Je vais ___ une pomme.',
    correctAnswer: 'manger',
    options: ['manger', 'mangé', 'mange', 'manges'],
  },
  {
    id: '23',
    type: 'conjugaison',
    verb: 'aller',
    category: 'aller',
    pronoun: 'Tu',
    tense: 'futur proche',
    sentence: 'Tu vas ___ au parc.',
    correctAnswer: 'aller',
    options: ['aller', 'allé', 'vas', 'va'],
  },
  {
    id: '24',
    type: 'conjugaison',
    verb: 'faire',
    category: 'faire',
    pronoun: 'Nous',
    tense: 'futur proche',
    sentence: 'Nous allons ___ du sport.',
    correctAnswer: 'faire',
    options: ['faire', 'fait', 'faisons', 'fais'],
  },
  {
    id: 'g1',
    type: 'grammaire',
    grammarType: 'genre',
    sentence: 'Le mot "Lune" est...',
    correctAnswer: 'Féminin',
    options: ['Masculin', 'Féminin'],
  },
  {
    id: 'g2',
    type: 'grammaire',
    grammarType: 'genre',
    sentence: 'Le mot "Soleil" est...',
    correctAnswer: 'Masculin',
    options: ['Masculin', 'Féminin'],
  },
  {
    id: 'g3',
    type: 'grammaire',
    grammarType: 'nombre',
    sentence: 'Le mot "Chats" est...',
    correctAnswer: 'Pluriel',
    options: ['Singulier', 'Pluriel'],
  },
  {
    id: 'g4',
    type: 'grammaire',
    grammarType: 'nombre',
    sentence: 'Le mot "Fusée" est...',
    correctAnswer: 'Singulier',
    options: ['Singulier', 'Pluriel'],
  },
  {
    id: 'g5',
    type: 'grammaire',
    grammarType: 'nature',
    sentence: 'Dans "Le petit chien", "chien" est un...',
    correctAnswer: 'Nom',
    options: ['Nom', 'Verbe', 'Déterminant'],
  },
  {
    id: 'g6',
    type: 'grammaire',
    grammarType: 'nature',
    sentence: 'Dans "Il mange une pomme", "mange" est un...',
    correctAnswer: 'Verbe',
    options: ['Nom', 'Verbe', 'Adjectif'],
  },
  {
    id: 'g7',
    type: 'grammaire',
    grammarType: 'nature',
    sentence: 'Dans "La grande maison", "grande" est un...',
    correctAnswer: 'Adjectif',
    options: ['Nom', 'Verbe', 'Adjectif'],
  },
  {
    id: 'g8',
    type: 'grammaire',
    grammarType: 'nature',
    sentence: 'Dans "Une voiture", "Une" est un...',
    correctAnswer: 'Déterminant',
    options: ['Nom', 'Déterminant', 'Verbe'],
  },
  {
    id: 'g9',
    type: 'grammaire',
    grammarType: 'sujet-verbe',
    sentence: 'Dans "Le chat dort", le sujet est...',
    correctAnswer: 'Le chat',
    options: ['Le chat', 'dort'],
  },
  {
    id: 'g10',
    type: 'grammaire',
    grammarType: 'sujet-verbe',
    sentence: 'Dans "Les enfants jouent", le verbe est...',
    correctAnswer: 'jouent',
    options: ['Les enfants', 'jouent'],
  },
  {
    id: 'g11',
    type: 'grammaire',
    grammarType: 'ponctuation',
    sentence: 'Quelle ponctuation va à la fin d\'une question ?',
    correctAnswer: '?',
    options: ['.', '!', '?'],
  },
  {
    id: 'g12',
    type: 'grammaire',
    grammarType: 'ponctuation',
    sentence: 'Quelle ponctuation marque la fin d\'une phrase simple ?',
    correctAnswer: '.',
    options: ['.', '!', '?'],
  },
  {
    id: 'g13',
    type: 'grammaire',
    grammarType: 'genre',
    sentence: 'Le mot "Ordinateur" est...',
    correctAnswer: 'Masculin',
    options: ['Masculin', 'Féminin'],
  },
  {
    id: 'g14',
    type: 'grammaire',
    grammarType: 'genre',
    sentence: 'Le mot "Table" est...',
    correctAnswer: 'Féminin',
    options: ['Masculin', 'Féminin'],
  },
  {
    id: 'g15',
    type: 'grammaire',
    grammarType: 'nombre',
    sentence: 'Le mot "Oiseaux" est...',
    correctAnswer: 'Pluriel',
    options: ['Singulier', 'Pluriel'],
  },
  {
    id: 'g16',
    type: 'grammaire',
    grammarType: 'nombre',
    sentence: 'Le mot "Fleur" est...',
    correctAnswer: 'Singulier',
    options: ['Singulier', 'Pluriel'],
  },
  {
    id: 'g17',
    type: 'grammaire',
    grammarType: 'nature',
    sentence: 'Un mot qui désigne une action est un...',
    correctAnswer: 'Verbe',
    options: ['Nom', 'Verbe', 'Déterminant'],
  },
  {
    id: 'g18',
    type: 'grammaire',
    grammarType: 'nature',
    sentence: '"Paris" est un...',
    correctAnswer: 'Nom propre',
    options: ['Nom commun', 'Nom propre', 'Verbe'],
  },
  {
    id: 'g19',
    type: 'grammaire',
    grammarType: 'nature',
    sentence: '"Garçon" est un...',
    correctAnswer: 'Nom commun',
    options: ['Nom commun', 'Nom propre', 'Adjectif'],
  },
  {
    id: 'g20',
    type: 'grammaire',
    grammarType: 'nature',
    sentence: '"Rouge" est un...',
    correctAnswer: 'Adjectif',
    options: ['Nom', 'Verbe', 'Adjectif'],
  },
  {
    id: 'p1',
    type: 'conjugaison',
    verb: 'dire',
    category: 'dire',
    pronoun: 'Je',
    tense: 'passé composé',
    sentence: 'J\'ai ___ la vérité.',
    correctAnswer: 'dit',
    options: ['dit', 'dis', 'dite', 'disent'],
  },
  {
    id: 'p2',
    type: 'conjugaison',
    verb: 'venir',
    category: 'venir',
    pronoun: 'Tu',
    tense: 'passé composé',
    sentence: 'Tu es ___ me voir.',
    correctAnswer: 'venu',
    options: ['venu', 'viens', 'venez', 'venus'],
  },
  {
    id: 'f1',
    type: 'conjugaison',
    verb: 'dire',
    category: 'dire',
    pronoun: 'Elle',
    tense: 'futur proche',
    sentence: 'Elle va ___ son secret.',
    correctAnswer: 'dire',
    options: ['dire', 'dit', 'disent', 'disait'],
  },
  {
    id: 'f2',
    type: 'conjugaison',
    verb: 'venir',
    category: 'venir',
    pronoun: 'Ils',
    tense: 'futur proche',
    sentence: 'Ils vont ___ demain.',
    correctAnswer: 'venir',
    options: ['venir', 'venu', 'viennent', 'venons'],
  },
  {
    id: 'g21',
    type: 'grammaire',
    grammarType: 'ponctuation',
    sentence: 'Quelle ponctuation exprime la surprise ?',
    correctAnswer: '!',
    options: ['.', '!', '?'],
  },
  {
    id: 'g22',
    type: 'grammaire',
    grammarType: 'sujet-verbe',
    sentence: 'Dans "La petite fille chante", le verbe est...',
    correctAnswer: 'chante',
    options: ['fille', 'chante', 'petite'],
  },
];
